AUTH0_URL: auth-dev.mozilla.auth0.com
AUDIENCE: https://person-api.sso.allizom.org
CIS_DYNAMODB_TABLE: CISStaging-VaultandStreams-IdentityVaultUsers-O35P6M8U9LNW
CIS_DYNAMODB_ARN: arn:aws:dynamodb:*:*:table/CISStaging-VaultandStreams-IdentityVaultUsers-O35P6M8U9LNW
